export const ACTION_TYPE1 = "ACTION_TYPE1";
export const USERDATA_LOAD = "USERDATA_LOAD";
export const USERDATA_LOAD_SUCCESS = "USERDATA_LOAD_SUCCESS";
export const USERDATA_LOAD_ERROR = "USERDATA_LOAD_ERROR";
